Remove XFAIL for mat_cbuffer-swizzle.f32.test
The XFAIL here seemed to be for the wrong issue, as this was actually
failing SPIR-V validation like so:

```
error: line 276: Reached non-composite type while indexes still remain
                 to be traversed.
  %186 = OpCompositeInsert %float %185 %81 0
```

This is no longer occuring after llvm/llvm-project#198330, so it looks
like this has been fixed.